esphome:
  name: klima-box

esp32:
  board: esp32-c3-devkitm-1
  variant: esp32c3
  framework:
    type: arduino

wifi:
  ssid: "M1"
  password: "ManLsc24?"

  # Záchranný hotspot (kdyby mobil nebyl po ruce)
  ap:
    ssid: "Baguette"
    password: "ytongytongytong"

captive_portal:

# Důležité pro komunikaci s Home Assistantem
api:

ota:
  platform: "esphome"
  password: "ytong"

logger:

# --- NASTAVENÍ KOMUNIKACE ---

# 1. I2C sběrnice pro AHT20 a BMP280
i2c:
  scl: 5
  sda: 6
  scan: true

# 2. UART sběrnice pro zelený měřič spotřeby (PZEM)
uart:
  rx_pin: 20 # Pin, kam jde TX z PZEM
  tx_pin: 21 # Pin, kam jde RX z PZEM
  baud_rate: 9600

# 3. Sběrnice pro voděodolné teploměry (přes nový one_wire)
one_wire:
  - platform: gpio
    pin: 2
    id: ow_bus_core
  - platform: gpio
    pin: 3
    id: ow_bus_out


modbus:
  

# --- SENZORY (ČTENÍ HODNOT) ---
sensor:
  # Voděodolný teploměr 1 (Pin 2)
  - platform: dallas_temp
    one_wire_id: ow_bus_core
    name: "Teplota (Core)"

  # Voděodolný teploměr 2 (Pin 3)
  - platform: dallas_temp
    one_wire_id: ow_bus_out
    name: "Teplota (Out)"

  # Senzor AHT20
  - platform: aht10
    temperature:
      name: "Teplota (AHT)"
    humidity:
      name: "Vlhkost (AHT)"
    update_interval: 10s

  # Senzor BMP280 (nový zápis pro I2C)
  - platform: bmp280_i2c
    temperature:
      name: "Teplota (BMP)"
    pressure:
      name: "Tlak (BMP)"
    address: 0x77 # Kdyby nefungoval, zkuste změnit na 0x76
    update_interval: 10s


# Zelený měřič spotřeby (NOVÝ ZÁPIS PRO VERZI V3)
  - platform: pzemac
    current:
      name: "Proud (PZEM)"
    voltage:
      name: "Napětí (PZEM)"
    power:
      name: "Výkon (PZEM)"
    energy:
      name: "Spotřebovaná energie (PZEM)"
    frequency:
      name: "Frekvence (PZEM)"
    update_interval: 5s

# --- VÝSTUPY (OVLÁDÁNÍ) ---
switch:
  # Velká modrá relátka
  - platform: gpio
    pin: 7
    name: "Relé (Větrák)"
    id: relay_vetrak
    inverted: false # Změňte na true, pokud spínají obráceně

  - platform: gpio
    pin: 10
    name: "Relé (Ohřívač)"
    id: relay_ohrivac
    inverted: false

  # Ovládání modulu L9110 (malý větráček)
  - platform: gpio
    pin: 0
    name: "Malý větráček (Vpřed)"
    id: vetracek_vpred
    interlock: [vetracek_vzad] # Bezpečnostní pojistka
    
  - platform: gpio
    pin: 1
    name: "Malý větráček (Vzad)"
    id: vetracek_vzad
    interlock: [vetracek_vpred] # Bezpečnostní pojistka